### ISSUE TITLE
Search by number or article number doesn't seem to work

### ISSUE THREAD

**Issue by elmaxe** [larsha/bolaget.io#11]
Using
```http
GET /products/:nr
Host: bolaget.io
```
doesn't seem to work.

`https://bolaget.io/products/:nr` returns 404 error.
`https://bolaget.io/products/:1458` returns 404 error.
`https://bolaget.io/products/nr=1458` returns 404 error.
`https://bolaget.io/products?nr=1458` returns same data as `https://bolaget.io/products/`.
`https://bolaget.io/products/1458` returns 404 error.
`https://bolaget.io/products/nr:1458` returns 404 error.

What is the correct way to query by id number? Or is it not working?

**Comment by larsha** [comment]
Hi,

The URL should look like this: https://bolaget.io/products/3042103

And it’s the “nr” property returned from https://bolaget.io/products/ that should be used. Not the “article_id” or “article_nr”.

Let me know if you get it to work.

**Comment by elmaxe** [comment]
Thanks! That works.

Why no search by "article_nr" though? It is the id that is visible on systembolaget.se and would be nice if you could query it

**Comment by larsha** [comment]
Yes that sounds better indeed, I’ll have to look into this, can’t remember why I didn’t implement it that way now. Maybe it’s time for a major version bump, with this change in it.

Or extending the functionality so it tries to use both ids for the search, maybe that is better, that way we don’t implement any breaking changes. This should be possible because the ids seems to be related.

A PR is always welcome :)

**Comment by larsha** [comment]
@elmaxe I can have a look at this, just went through some code, will let you know when it is fixed, probably during the weekend.

**Comment by larsha** [comment]
@elmaxe This is fixed in b2de9ef9dbbdebd7b3ae776477dc52def095fbef and released now.

**Comment by elmaxe** [comment]
Fantastic!
